### ISSUE TITLE
Some shortcut combinations make one of them not to work

### ISSUE THREAD

**Issue by pablopunk** [pablopunk/SwiftShift#12]
![CleanShot 2023-12-30 at 20 18 37@2x](https://github.com/pablopunk/SwiftShift/assets/4324982/49fdaa41-000c-4b20-ac55-5fab7a64b5fa)

**Comment by Bryceshaw06** [comment]
Same issue here - M1 Macbook Air on latest version

**Comment by pablopunk** [comment]
@Bryceshaw06 @xezrunner Can you guys try [v0.10.0](https://github.com/pablopunk/SwiftShift/releases/tag/0.10.0)? Let me know if the issues are fixed :)

**Comment by Bryceshaw06** [comment]
@pablopunk It did not fix it for me. I am on the latest version, and the commands I'm trying to use are "Command" for "Move" and "Alt+Command" for "Resize". https://share.cleanshot.com/wGq9Jxst

**Comment by xezrunner** [comment]
Can confirm that there is still an issue with shortcut overlap.

https://github.com/pablopunk/SwiftShift/assets/8061077/20ffc71d-47d5-497e-9de5-675bdab1e4c7

However, on Ventura, the app now works when screen recording as well, something it did not do with one of the initial versions.

**Comment by pablopunk** [comment]
This seems to be a different issue to the one I solved (which was just triggering both actions at the same time, so one would shadow the other one).

This one only happens when one shortcut contains the other one (⌘⇪ contains ⌘) but I'm having a hard time fixing the code.

https://github.com/pablopunk/SwiftShift/blob/05305abd56a80e4aa541d82a08b6e7fcaf02253c/Swift%20Shift/src/shortchuts/ShortcutsManager.swift#L112-L116

Both shortcuts pass the second check because ⌘⇪ contains ⌘, so I think by inverting the check (⌘ contains ⌘⇪) it should work but the AlgebraSet might not work as I think 😅, cause this makes no shortcut to be triggered:

```diff
 if event.modifierFlags.isDisjoint(with: shortcut.modifierFlags) { 
     MouseTracker.shared.stopTracking(for: action) 
-} else if event.modifierFlags.contains(shortcut.modifierFlags) { 
+} else if shortcut.modifierFlags.contains(event.modifierFlags) { 
     MouseTracker.shared.startTracking(for: action) 
 } 
```

**Comment by pablopunk** [comment]
Well I asked ChatGPT and it completely solved the issue by using something I didn't know about ([converting the events using `.deviceIndependentFlagsMask`](https://github.com/pablopunk/SwiftShift/commit/d651215608f585eded51e15171d77a962cd9caa1)). Should have done that much earlier.

**Comment by pablopunk** [comment]
@xezrunner @Bryceshaw06 Please check out the latest release and see if the issue is finally fixed 🙏🏻  https://github.com/pablopunk/SwiftShift/releases/tag/0.13.0

**Comment by Bryceshaw06** [comment]
Works great @pablopunk ! Thanks for the fix!
