### ISSUE TITLE
Compatibility with previous macOS versions

### ISSUE THREAD

**Issue by xezrunner** [pablopunk/SwiftShift#14]
Trying to run the application on Ventura results in the following dialog box:

![image](https://github.com/pablopunk/SwiftShift/assets/8061077/460874ac-9873-4403-93cc-958ec376b3f4)

For those of us that can't update to Sonoma for software compatibility reasons, is it possible for the app to lower its minimum macOS version requirements, or is the app making use of APIs that are only available starting with Sonoma?

**Comment by pablopunk** [comment]
@xezrunner fixed. Now the minimum version is macOS 13.0 (couldn't go lower cause the way I handle login items is only compatible with Ventura+).

You can download it on [github](https://github.com/pablopunk/SwiftShift/releases/tag/0.9.0) or [swiftshift](https://swiftshift.app). Let me know if it works, I don't have Ventura installed

**Comment by xezrunner** [comment]
It certainly launches and works for the most part on Ventura now!

<img width="1440" alt="image" src="https://github.com/pablopunk/SwiftShift/assets/8061077/6956eb72-c7ad-4636-8101-ddc04718f63b">

There are some quirks, such as with move and resize being assigned at the same time, resize doesn't seem to work.
If I unbind move and have just resize bound, it works. If I then stop screen recording and bind move then, it works again.

Not sure if these are specific issues to Ventura.

https://github.com/pablopunk/SwiftShift/assets/8061077/24c963f7-dd57-4957-8fe8-80bb7b533bc6

**Comment by xezrunner** [comment]
https://github.com/pablopunk/SwiftShift/issues/12 might be the issue with resize not working when both are bound.
