### ISSUE TITLE
Local build failure

### ISSUE THREAD

**Issue by slashbeast** [pablopunk/SwiftShift#15]
Hi, thanks for sharing code. Would you consider adding some build instructions to the project?

I've tried to build it with `xcodebuild -project 'Swift Shift.xcodeproj' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO` but this does not seems to be working, from the look of it, seems like the local dependencies are missing

```
Copy /Users/piotr/src/SwiftShift/build/Release/Swift\ Shift.app/Contents/Resources/ShortcutRecorder_ShortcutRecorder.bundle /Users/piotr/src/SwiftShift/build/Release/ShortcutRecorder_ShortcutRecorder.bundle (in target 'Swift Shift' from project 'Swift Shift')
    cd /Users/piotr/src/SwiftShift
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/piotr/src/SwiftShift/build/Release/ShortcutRecorder_ShortcutRecorder.bundle /Users/piotr/src/SwiftShift/build/Release/Swift\ Shift.app/Contents/Resources
error: /Users/piotr/src/SwiftShift/build/Release/ShortcutRecorder_ShortcutRecorder.bundle: No such file or directory (in target 'Swift Shift' from project 'Swift Shift')

```

**Comment by pablopunk** [comment]
Hey! Sorry I'm new to swift/xcode and I have no idea how to build stuff from the terminal. I just use Xcode to build it, does that work for you?

**Comment by pablopunk** [comment]
Closing this one. Feel free to open it again.

**Comment by pablopunk** [comment]
@slashbeast in case you're still interested, this works for me:

```shell
xcodebuild -workspace Swift\ Shift.xcodeproj/project.xcworkspace -scheme Swift\ Shift
```
