### ISSUE TITLE
Allow adding mouse buttons to shortcuts

### ISSUE THREAD

**Issue by xezrunner** [pablopunk/SwiftShift#16]
This is a feature request.

It would be very convenient to allow adding a mouse button next to modifier keys for initiating the move and resize actions.

This would replicate the same behavior as it is on Linux, where holding the Meta (or sometimes Alt) key and dragging with either the left, right or middle mouse buttons initiates the move and resize actions.
[AltSnap (Windows)](https://github.com/RamonUnch/AltSnap) also replicates this behavior.

An intuitive way I thought of is if during editing a shortcut, the user could hold a modifier key (such as Command), then click the desired mouse button (such as the left mouse button) while pointing into the shortcut field.

<img width="274" alt="image" src="https://github.com/pablopunk/SwiftShift/assets/8061077/e7a467c6-b7f6-4d8e-9a8f-e2b39523ddff">

**Comment by pablopunk** [comment]
hey! Thanks for the request! That's interesting, I might try to implement it. I think UI-wise I could keep it simple and add a dropdown on each shortcut for `Mouse: none|left|right`

**Comment by Designator-Ol** [comment]
Do you still plan on integrating that feature and if so do you have an ETA ?

Greetings,
Desi

**Comment by pablopunk** [comment]
@Designator-Ol @xezrunner Done. It's already available on [0.25.0](https://github.com/pablopunk/SwiftShift/releases/tag/0.25.0)
