### ISSUE TITLE
Can you add support for monterey ?

### ISSUE THREAD

**Issue by krushnadeore** [pablopunk/SwiftShift#19]
<img width="265" alt="Screenshot 2024-01-02 at 12 29 28 PM" src="https://github.com/pablopunk/SwiftShift/assets/73570192/dc28919f-0cbe-4563-a3fa-a58fc44d3c69">

**Comment by pablopunk** [comment]
Sorry, I'm trying to downgrade it but there's a few of things I use are dependent on macOS 12+:

* `LaunchAtLogin` library (to handle login items)
* The `MenuBarExtra` API to handle the menubar item

I don't know how to get around those but I'm guessing it will require maintaining two different versions of the UI, one for macOS 12 and one for macOS 13+.

I'm open to PRs if someones wants to refactor it :)

**Comment by xezrunner** [comment]
> The MenuBarExtra API to handle the menubar item

https://github.com/pablopunk/SwiftShift/blob/300e726a8f267dcd264e3292dfecd0faa02ddb9a/Swift%20Shift/src/app/App.swift#L10-L13

I wonder if using an `if #available(macOS 10.13, *)` or similar attribute would allow for using a regular window on older macOS versions instead. Could make the menubar icon appear and just act as a shortcut to bring a regular window up, with the same View as the menubar View.

**Comment by pablopunk** [comment]
So I've been working on this one, but I have bad news. I ended up creating a new target just to compile it for older versions and work around all of those issues (menubar logic and login items logic). I did get around them, but then I realized the move/resize logic wouldn't work at all. Not sure why, probably related to how the accessibility API worked before macOS 13.

That's the core part of this app, so I don't want to refactor it all just to support macOS 12. It was becoming a whole other project. That doesn't mean I don't want it to happen, but I'm not going to create a whole new app just for this use case. Feel free to clone this repo and reuse any code you need to make it happen 🙏
