### ISSUE TITLE
Resizing from top/left

### ISSUE THREAD

**Issue by coreORB** [pablopunk/SwiftShift#21]
Would it be possible to add new shortcut to resize windows from top/left?
Now when I want to place window in remaining space on right side of screen I have to move it, resize, check if it fits and repeat moving ad resizing.
With new feature one could move window to right edge, resize from left side and done :).

**Comment by pablopunk** [comment]
@coreORB interesting! would you like to have an option to chose "where to resize from" or both options at the same time? i.e one shortcut for bottom-right resizing and another one for top-left

**Comment by pablopunk** [comment]
yeah, but the app actually allows you to set any shortcut, not only modifiers (i.e ⌘+M), so the UI should be generic. I might implement a way to extend a shortcut (similar to what I'm doing in https://github.com/pablopunk/SwiftShift/pull/22) so it allows more customization. In this case it would require to allow the user to split a shortcut into 2 (left-top resizing vs right-bottom)

**Comment by coreORB** [comment]
Sure, more customization is always welcomed ;).
I wrote about shortcuts, because I'm currently using two of those and find them intuitive. IMO third one would complete it nicely and those would make great defaults.
