### ISSUE TITLE
Pressing the shortcut without the mouse should not do anything

### ISSUE THREAD

**Issue by pablopunk** [pablopunk/SwiftShift#23]
Right now if you press any shortcut it will focus the app under the cursor, without moving your mouse at all. This shouldn't happen as it prevents some shortcut combinations from happening in some apps

**Comment by SteveMattan** [comment]
Hello, perhaps this is the same issue: when I press the initial key of the shortcut SwiftShift activates.

I have Move set as "Shift M" and Resize as "Caps Lock R" (where Caps Lock is set a hyper key, ⇧⌘⌃⌥, via Karabiner Elements). If I press Shift, SwiftShift is invoked and I can move the window under the cursor without pressing M. Likewise pressing Caps Lock without R allows me to resize a window.

macOS 14.2.1
SwiftShift 0.17.0

Let me know if you would like any additional information.

**Comment by pablopunk** [comment]
@SteveMattan ah that might be a separate issue. I think I'm triggering the shortcut anyway if all modifiers (of any shortcut) are pressed. Will open a new issue

**Comment by pablopunk** [comment]
@SteveMattan can you try [v0.19.0](https://github.com/pablopunk/SwiftShift/releases/tag/0.19.0)?

**Comment by SteveMattan** [comment]
@pablopunk That fixed it. Thank you.
