### ISSUE TITLE
Remove Sparkle Sandboxing configuration

### ISSUE THREAD

**Issue by zorgiepoo** [pablopunk/SwiftShift#34]
Due to a sandboxing issue new to macOS Sonoma, users may see a one-time warning when checking for updates about "Downloader" differs from previously opened versions. See https://github.com/sparkle-project/Sparkle/discussions/2514 for more information.

SwiftShift can simply resolve this issue by removing its sandboxed configuration for Sparkle because SwiftShift itself is not sandboxed. This involves removing the SUEnableDownloaderService and SUEnableInstallerLauncherService keys in its Info.plist along with removing the `com.apple.security.temporary-exception.mach-lookup.global-name` key in its entitlements file. These settings were retrieved from [Sparkle's Sandboxing guide](https://sparkle-project.org/documentation/sandboxing/) but again, this app is not sandboxed.

**Comment by pablopunk** [comment]
hey @zorgiepoo, thank you for taking the time to explain it! Would you say this [will](https://github.com/pablopunk/SwiftShift/pull/37) be enough? Or should I just remove the entitlements file too?

**Comment by pablopunk** [comment]
> Shouldn't matter if you remove an empty entitlements file or not

Turns out Xcode complains if it's not there. Anyway, I tested and updating works, so I'll include this in the next release. Thanks for the help!
