### ISSUE TITLE
To use fn modifier as one of the keys to resize or move

### ISSUE THREAD

**Issue by Dhairy2003** [pablopunk/SwiftShift#46]
I use an external keyboard and the fn key is pretty useless . By having the fn key to move/resize will save me the trouble to use another modifier or gap of modifiers.

**Comment by pablopunk** [comment]
hey @Dhairy2003, I'm sorry but AFAIK the `fn` key doesn't really do anything unless it's pressed in combination with another key, so it doesn't do much on its own. Or at least there's no event it's sending that I can catch to move/resize windows :(

Feel free to open another issue/PR if you think there's a workaround or more info I don't know about

**Comment by nmder** [comment]
Not sure if it'll help, but this obscure app with similar functionalities does it: https://mikkelmalmberg.com/moves

Thanks!!
