### ISSUE TITLE
What about... 9️⃣ quadrants? 😁

### ISSUE THREAD

**Issue by roelvangils** [pablopunk/SwiftShift#51]
https://github.com/pablopunk/SwiftShift/assets/103744/1e6cdb65-7c3b-4f10-a4b6-b8066074f57e

**Comment by roelvangils** [comment]
When your mouse pointer is in the window's border area:

- Q1: Resize from the **top-left** corner when you hold modifier keys.
- Q2: Increase the window's **height** by extending the top area (preserving the width) when you hold modifier keys.
- Q3: Resize from the **top-right** corner when you hold modifier keys.
- Q4: Increase the window's **width** by extending the left area (preserving the width) when you hold modifier keys.
- Q5 (the special one):
  - When you move your mouse **up or down** while holding the modifier keys, the window **height increases or decreases** in **both directions** (but the width is preserved).
  - When you move your mouse **left or right** while holding the modifier keys, the window **width increases or decreases** in **both directions** (but the height is preserved).
  
(And the rest is self-explanatory)

What do you think?

**Comment by danini-the-panini** [comment]
This matches functionality in most Linux floating window managers, and AltSnap on windows

**Comment by roelvangils** [comment]
> This matches functionality in most Linux floating window managers, and AltSnap on windows

Really? I didn't even know! 😆

**Comment by pablopunk** [comment]
@roelvangils that's fair, I was lazy to implement it like that at the first try.

But honestly I've just wrote your description to ChatGPT with my code attached and it made all the changes (and it works, first try 🥳)

I'll make a PR now with the new changes. BTW how did you create that animation? I'd love to showcase it in [swiftshift.app](https://swiftshift.app), and I would love a light background alternative too 🌝

https://github.com/pablopunk/SwiftShift/assets/4324982/2699bcf9-3fbf-49b7-bf2d-d3181fd357f8

**Comment by pablopunk** [comment]
Released in 0.25.0

**Comment by roelvangils** [comment]
> But honestly I've just wrote your description to ChatGPT with my code attached and it made all the changes (and it works, first try 🥳)

Amazing! Yes, these are the things LLMs are so good at..

> I'll make a PR now with the new changes. 

Just installed the update. Works like a charm! 😻

> BTW how did you create that animation? I'd love to showcase it in swiftshift.app, and I would love a light background alternative too 🌝

I used Apple Keynote for that. I saw your website already looks quite nice, but feel free to use it! Or let met know which background (and/or colors) you prefer and I'll make a nicer version for you (dark and light mode), as a way to say thanks for implementing my feature request.

**Comment by pablopunk** [comment]
> Just installed the update. Works like a charm! 😻

I'm glad!

> I used Apple Keynote for that

lol that's awesome, I've never thought about using it for animations. I might give it a try. If you feel like doing it, just do something that makes sense for the style of [swiftshift.app](https://swiftshift.app), even tho the design is all over the place right now 😅

**Comment by pablopunk** [comment]
I ended up creating the animations with Figma and they turned out ok


https://github.com/pablopunk/SwiftShift/assets/4324982/ac263df3-0868-41a6-b528-a423653d1e4b


Not really showcasing the 9 quadrants but it's good enough

**Comment by roelvangils** [comment]
That looks great! Sorry for not following up on my suggestion to create it for you! Time.... 😉

**Comment by pablopunk** [comment]
@roelvangils no worries! I'm also struggling to find time for this project 😓
