### ISSUE TITLE
Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle

### ISSUE THREAD

**Issue by danini-the-panini** [pablopunk/SwiftShift#52]
I tried cloning the project and running it in Xcode, but I'm getting this error when I try run it.

I've tried setting Runpath Search Paths to `@loader_path/../Frameworks` according to a bunch of Sparkle issues, but that doesn't seem to work.

Any ideas?

**Comment by pablopunk** [comment]
Honestly no idea, I know very little about Xcode (this is my first project on it). I installed the project on another Mac and I had no issues. What version of macOS/Xcode do you have?

**Comment by danini-the-panini** [comment]
Version 15.3 (15E204a)

I just cloned the project, opened the xcodeproj, set the signing to None / Sign to run locally, reset package cache, and clicked "Run"

**Comment by pablopunk** [comment]
Ok I can reproduce it now. Disable "Library Validation" in the entitlements file.

`Swift_Shift.entitlements` → Add an item → name it `com.apple.security.cs.disable-library-validation` → type `Boolean` → value `YES`

Don't commit it like that. But it should allow you to run it locally 👍🏻

**Comment by pablopunk** [comment]
Just FYI 
![CleanShot 2024-06-11 at 12 41 00](https://github.com/pablopunk/SwiftShift/assets/4324982/d623d448-16c9-4095-9f01-2717a6ef684c)

**Comment by danini-the-panini** [comment]
Ah I see, thank you!
